ZENDESK_SERVICE_NAMES = [
    'Auth broker',
    'Data Hub CRM',
    'Data Hub MI',
    'Data Hub OMIS',
    'Data Protection',
    'Datahub',
    'Digital Workspace',
    'Directory',
    'E-Exporting S00 Triage',
    'EIG',
    'Export Ops',
    'Export Vouchers',
    'Find a Supplier',
    'Great',
    'Invest in GB',
    'L. Letters',
    'Market Access',
    'Selling online overseas',
    'Single sign on',
]
