# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-30 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20181122_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='zendesk_service_name',
        ),
    ]
