# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 10:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.crypto
import django_cryptography.fields
import functools
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0004_remove_client_zendesk_service_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='access_key',
            field=django_cryptography.fields.encrypt(models.CharField(default=functools.partial(django.utils.crypto.get_random_string, *(), **{'length': 64}), max_length=128, verbose_name='API key')),
        ),
        migrations.AlterField(
            model_name='client',
            name='identifier',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='Sender ID'),
        ),
    ]
