# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 15:45
from __future__ import unicode_literals

import core.helpers
from django.db import migrations, models
import django_extensions.db.fields
import functools
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIClient',
            fields=[
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, null=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, null=True, verbose_name='modified')),
                ('client_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('access_key', models.CharField(default=functools.partial(core.helpers.make_random_string, *(), **{'length': 32}), help_text='Value is plain text during create. Hashed on edit.', max_length=128)),
                ('client_name', models.CharField(help_text='Human friendly name to help identify the record.', max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
