# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_sent',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
