# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-22 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0002_submission_is_sent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="is_sent",
            field=models.BooleanField(default=False),
        ),
    ]
