# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-05 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0003_auto_20181122_1553"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="form_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
