# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-09 09:15
from __future__ import unicode_literals

from django.db import migrations


def get_sender_email_address(submission_meta):
    action_name = submission_meta['action_name']
    if action_name == 'zendesk':
        return submission_meta['email_address']
    elif action_name == 'email':
        return submission_meta['reply_to'][0]
    elif action_name == 'gov-notify':
        return submission_meta['email_address']


def create_sender(apps, schema_editor):
    Submission = apps.get_model('submission', 'Submission')
    Sender = apps.get_model('submission', 'Sender')
    for submission in Submission.objects.filter(sender__isnull=True):
        try:
            email = get_sender_email_address(submission.meta)
        except (KeyError, IndexError):
            email = None
        if email:
            sender, _ = Sender.objects.get_or_create(email_address=email)
            submission.sender = sender
            submission.save()


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0009_auto_20190109_0904'),
    ]

    operations = [
        migrations.RunPython(create_sender, migrations.RunPython.noop),
    ]
