# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-10 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0010_auto_20190109_0915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sender',
            name='email_address',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
