# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-10-17 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submission', '0012_auto_20190705_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='sender',
            name='blacklisted_reason',
            field=models.CharField(blank=True, choices=[('MA', 'Manual'), ('IP', 'IP Restricted')], max_length=15, null=True),
        ),
    ]
